name: my_ecommerce
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  google_nav_bar: ^5.0.7
  flutter_screenutil: ^5.9.3
  smooth_page_indicator: ^1.2.1
  pin_code_fields: ^8.0.1
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Asset directories
  assets:
    - assets/images/
    - assets/icons/

  # Font definitions
  fonts:
    # 1. General Sans (Located in assets/font/)
    - family: GeneralSans
      fonts:
        - asset: assets/font/GeneralSans-Extralight.otf
          weight: 200
        - asset: assets/font/GeneralSans-ExtralightItalic.otf
          weight: 200
          style: italic

        - asset: assets/font/GeneralSans-Light.otf
          weight: 300
        - asset: assets/font/GeneralSans-LightItalic.otf
          weight: 300
          style: italic

        - asset: assets/font/GeneralSans-Regular.otf
          weight: 400
        - asset: assets/font/GeneralSans-Italic.otf
          weight: 400
          style: italic

        - asset: assets/font/GeneralSans-Medium.otf
          weight: 500
        - asset: assets/font/GeneralSans-MediumItalic.otf
          weight: 500
          style: italic

        - asset: assets/font/GeneralSans-Semibold.otf
          weight: 600
        - asset: assets/font/GeneralSans-SemiboldItalic.otf
          weight: 600
          style: italic

        - asset: assets/font/GeneralSans-Bold.otf
          weight: 700
        - asset: assets/font/GeneralSans-BoldItalic.otf
          weight: 700
          style: italic

    # 2. Nunito (Located in assets/font_feather/)
    - family: Nunito
      fonts:
        - asset: assets/font_feather/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/font_feather/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: assets/font_feather/Nunito-Light.ttf
          weight: 300
        - asset: assets/font_feather/Nunito-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/font_feather/Nunito-Regular.ttf
          weight: 400
        - asset: assets/font_feather/Nunito-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/font_feather/Nunito-Medium.ttf
          weight: 500
        - asset: assets/font_feather/Nunito-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/font_feather/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/font_feather/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/font_feather/Nunito-Bold.ttf
          weight: 700
        - asset: assets/font_feather/Nunito-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/font_feather/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/font_feather/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: assets/font_feather/Nunito-Black.ttf
          weight: 900
        - asset: assets/font_feather/Nunito-BlackItalic.ttf
          weight: 900
          style: italic

    # 3. Feather (Located in assets/font_feather/)
    - family: Feather
      fonts:
        - asset: assets/font_feather/Feather-Bold.ttf
          weight: 700